### ISSUE TITLE
Address 2 (apt. suite floor)

### ISSUE THREAD

**Issue by yonib05** [mkoryak/address-validator#6]
It would be nice if the validation could preserve this data so that if a user passes in any type of unique data it comes back within the validation.

**Comment by mkoryak** [comment]
this lib does not attempt to parse the input address string in any way, it lets google handle all of that. I think that you will find that trying to parse addresses is a very hard problem. 

If google api returns this information then I can return it, otherwise, it will never work correctly in all cases (like, addresses from other countries for example)
